# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: blog

description: My blog

author:
  name: wzq
  email: 297001985@qq.com
  github: wzq
  twitter: zhengqi
  # pinterest: wzq
  # linkedin: wzq
  bio: Simple blog.
  email_md5: 74dd73cd34dd5f0d87f1daac581cf60b

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: ""
paginate: 5 # pagination based on number of posts
paginate_path: "page:num"

safe: true

#highlighter: pygments

# Gems
gems: [jekyll-paginate]