# Site settings
title: WZQ
email: 297001985@qq.com
description: > # this means to ignore newlines until "baseurl:"
 The Most Simple Blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.baidu.com" # the base hostname & protocol for your site
twitter_username: zhengqi
github_username:  wzq

# Build settings
markdown: kramdown
