# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: wzq

description: My blog

author:
  name: wzq
  email: 297001985@qq.com
  github: wzq
  twitter: zhengqi
  pinterest: wzq
  linkedin: wzq
  bio: My simple blog.
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: ""
paginate: 5 # pagination based on number of posts
paginate_path: "page:num"